server:
  port: 8082

spring:
  application:
    name: games-service

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/games?currentSchema=sales
    username: postgres
    password: 123456